# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rankingservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rankingservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14rankingservice.proto\"_\n\tGetVPsReq\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06numVPs\x18\x02 \x01(\x05\x12\x18\n\x10rankingTechnique\x18\x03 \x01(\t\x12\x1c\n\x14\x65xecutedMeasurements\x18\x04 \x03(\t\"\"\n\nGetVPsResp\x12\x14\n\x03vps\x18\x01 \x03(\x0b\x32\x07.Source\"W\n\x06Source\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04site\x18\x03 \x01(\t\x12\x0f\n\x07ingress\x18\x04 \x01(\t\x12\x10\n\x08\x64istance\x18\x05 \x01(\x02\"u\n\rGetTargetsReq\x12\x12\n\nis_initial\x18\x01 \x01(\x08\x12\x19\n\x11is_only_addresses\x18\x02 \x01(\x08\x12 \n\x0cip_addresses\x18\x03 \x03(\x0b\x32\n.IPAddress\x12\x13\n\x0bgranularity\x18\x04 \x01(\t\"\x1f\n\tIPAddress\x12\x12\n\nip_address\x18\x01 \x01(\t\"!\n\x0eGetTargetsResp\x12\x0f\n\x07targets\x18\x01 \x03(\t2j\n\x07Ranking\x12#\n\x06getVPs\x12\n.GetVPsReq\x1a\x0b.GetVPsResp\"\x00\x12:\n\x15getTargetsFromHitlist\x12\x0e.GetTargetsReq\x1a\x0f.GetTargetsResp\"\x00\x62\x06proto3'
)




_GETVPSREQ = _descriptor.Descriptor(
  name='GetVPsReq',
  full_name='GetVPsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='GetVPsReq.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numVPs', full_name='GetVPsReq.numVPs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rankingTechnique', full_name='GetVPsReq.rankingTechnique', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executedMeasurements', full_name='GetVPsReq.executedMeasurements', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=119,
)


_GETVPSRESP = _descriptor.Descriptor(
  name='GetVPsResp',
  full_name='GetVPsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vps', full_name='GetVPsResp.vps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=155,
)


_SOURCE = _descriptor.Descriptor(
  name='Source',
  full_name='Source',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='Source.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Source.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='site', full_name='Source.site', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ingress', full_name='Source.ingress', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='Source.distance', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=244,
)


_GETTARGETSREQ = _descriptor.Descriptor(
  name='GetTargetsReq',
  full_name='GetTargetsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_initial', full_name='GetTargetsReq.is_initial', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_only_addresses', full_name='GetTargetsReq.is_only_addresses', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_addresses', full_name='GetTargetsReq.ip_addresses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='GetTargetsReq.granularity', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=363,
)


_IPADDRESS = _descriptor.Descriptor(
  name='IPAddress',
  full_name='IPAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='IPAddress.ip_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=396,
)


_GETTARGETSRESP = _descriptor.Descriptor(
  name='GetTargetsResp',
  full_name='GetTargetsResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='targets', full_name='GetTargetsResp.targets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=431,
)

_GETVPSRESP.fields_by_name['vps'].message_type = _SOURCE
_GETTARGETSREQ.fields_by_name['ip_addresses'].message_type = _IPADDRESS
DESCRIPTOR.message_types_by_name['GetVPsReq'] = _GETVPSREQ
DESCRIPTOR.message_types_by_name['GetVPsResp'] = _GETVPSRESP
DESCRIPTOR.message_types_by_name['Source'] = _SOURCE
DESCRIPTOR.message_types_by_name['GetTargetsReq'] = _GETTARGETSREQ
DESCRIPTOR.message_types_by_name['IPAddress'] = _IPADDRESS
DESCRIPTOR.message_types_by_name['GetTargetsResp'] = _GETTARGETSRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetVPsReq = _reflection.GeneratedProtocolMessageType('GetVPsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETVPSREQ,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:GetVPsReq)
  })
_sym_db.RegisterMessage(GetVPsReq)

GetVPsResp = _reflection.GeneratedProtocolMessageType('GetVPsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETVPSRESP,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:GetVPsResp)
  })
_sym_db.RegisterMessage(GetVPsResp)

Source = _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
  'DESCRIPTOR' : _SOURCE,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:Source)
  })
_sym_db.RegisterMessage(Source)

GetTargetsReq = _reflection.GeneratedProtocolMessageType('GetTargetsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETTARGETSREQ,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:GetTargetsReq)
  })
_sym_db.RegisterMessage(GetTargetsReq)

IPAddress = _reflection.GeneratedProtocolMessageType('IPAddress', (_message.Message,), {
  'DESCRIPTOR' : _IPADDRESS,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:IPAddress)
  })
_sym_db.RegisterMessage(IPAddress)

GetTargetsResp = _reflection.GeneratedProtocolMessageType('GetTargetsResp', (_message.Message,), {
  'DESCRIPTOR' : _GETTARGETSRESP,
  '__module__' : 'rankingservice_pb2'
  # @@protoc_insertion_point(class_scope:GetTargetsResp)
  })
_sym_db.RegisterMessage(GetTargetsResp)



_RANKING = _descriptor.ServiceDescriptor(
  name='Ranking',
  full_name='Ranking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=433,
  serialized_end=539,
  methods=[
  _descriptor.MethodDescriptor(
    name='getVPs',
    full_name='Ranking.getVPs',
    index=0,
    containing_service=None,
    input_type=_GETVPSREQ,
    output_type=_GETVPSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTargetsFromHitlist',
    full_name='Ranking.getTargetsFromHitlist',
    index=1,
    containing_service=None,
    input_type=_GETTARGETSREQ,
    output_type=_GETTARGETSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKING)

DESCRIPTOR.services_by_name['Ranking'] = _RANKING

# @@protoc_insertion_point(module_scope)
