// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rankingservice.proto

package rankingservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetVPsReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	NumVPs               int32    `protobuf:"varint,2,opt,name=numVPs,proto3" json:"numVPs,omitempty"`
	RankingTechnique     string   `protobuf:"bytes,3,opt,name=rankingTechnique,proto3" json:"rankingTechnique,omitempty"`
	ExecutedMeasurements []string `protobuf:"bytes,4,rep,name=executedMeasurements,proto3" json:"executedMeasurements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVPsReq) Reset()         { *m = GetVPsReq{} }
func (m *GetVPsReq) String() string { return proto.CompactTextString(m) }
func (*GetVPsReq) ProtoMessage()    {}
func (*GetVPsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{0}
}

func (m *GetVPsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVPsReq.Unmarshal(m, b)
}
func (m *GetVPsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVPsReq.Marshal(b, m, deterministic)
}
func (m *GetVPsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVPsReq.Merge(m, src)
}
func (m *GetVPsReq) XXX_Size() int {
	return xxx_messageInfo_GetVPsReq.Size(m)
}
func (m *GetVPsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVPsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVPsReq proto.InternalMessageInfo

func (m *GetVPsReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetVPsReq) GetNumVPs() int32 {
	if m != nil {
		return m.NumVPs
	}
	return 0
}

func (m *GetVPsReq) GetRankingTechnique() string {
	if m != nil {
		return m.RankingTechnique
	}
	return ""
}

func (m *GetVPsReq) GetExecutedMeasurements() []string {
	if m != nil {
		return m.ExecutedMeasurements
	}
	return nil
}

type GetVPsResp struct {
	Vps                  []*Source `protobuf:"bytes,1,rep,name=vps,proto3" json:"vps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetVPsResp) Reset()         { *m = GetVPsResp{} }
func (m *GetVPsResp) String() string { return proto.CompactTextString(m) }
func (*GetVPsResp) ProtoMessage()    {}
func (*GetVPsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{1}
}

func (m *GetVPsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVPsResp.Unmarshal(m, b)
}
func (m *GetVPsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVPsResp.Marshal(b, m, deterministic)
}
func (m *GetVPsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVPsResp.Merge(m, src)
}
func (m *GetVPsResp) XXX_Size() int {
	return xxx_messageInfo_GetVPsResp.Size(m)
}
func (m *GetVPsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVPsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVPsResp proto.InternalMessageInfo

func (m *GetVPsResp) GetVps() []*Source {
	if m != nil {
		return m.Vps
	}
	return nil
}

type Source struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`
	Ingress              string   `protobuf:"bytes,4,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Distance             float32  `protobuf:"fixed32,5,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{2}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Source) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Source) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *Source) GetIngress() string {
	if m != nil {
		return m.Ingress
	}
	return ""
}

func (m *Source) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type GetTargetsReq struct {
	IsInitial            bool         `protobuf:"varint,1,opt,name=is_initial,json=isInitial,proto3" json:"is_initial,omitempty"`
	IsOnlyAddresses      bool         `protobuf:"varint,2,opt,name=is_only_addresses,json=isOnlyAddresses,proto3" json:"is_only_addresses,omitempty"`
	IpAddresses          []*IPAddress `protobuf:"bytes,3,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Granularity          string       `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTargetsReq) Reset()         { *m = GetTargetsReq{} }
func (m *GetTargetsReq) String() string { return proto.CompactTextString(m) }
func (*GetTargetsReq) ProtoMessage()    {}
func (*GetTargetsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{3}
}

func (m *GetTargetsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetsReq.Unmarshal(m, b)
}
func (m *GetTargetsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetsReq.Marshal(b, m, deterministic)
}
func (m *GetTargetsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetsReq.Merge(m, src)
}
func (m *GetTargetsReq) XXX_Size() int {
	return xxx_messageInfo_GetTargetsReq.Size(m)
}
func (m *GetTargetsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetsReq proto.InternalMessageInfo

func (m *GetTargetsReq) GetIsInitial() bool {
	if m != nil {
		return m.IsInitial
	}
	return false
}

func (m *GetTargetsReq) GetIsOnlyAddresses() bool {
	if m != nil {
		return m.IsOnlyAddresses
	}
	return false
}

func (m *GetTargetsReq) GetIpAddresses() []*IPAddress {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

func (m *GetTargetsReq) GetGranularity() string {
	if m != nil {
		return m.Granularity
	}
	return ""
}

type IPAddress struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPAddress) Reset()         { *m = IPAddress{} }
func (m *IPAddress) String() string { return proto.CompactTextString(m) }
func (*IPAddress) ProtoMessage()    {}
func (*IPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{4}
}

func (m *IPAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPAddress.Unmarshal(m, b)
}
func (m *IPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPAddress.Marshal(b, m, deterministic)
}
func (m *IPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPAddress.Merge(m, src)
}
func (m *IPAddress) XXX_Size() int {
	return xxx_messageInfo_IPAddress.Size(m)
}
func (m *IPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_IPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_IPAddress proto.InternalMessageInfo

func (m *IPAddress) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type GetTargetsResp struct {
	Targets              []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTargetsResp) Reset()         { *m = GetTargetsResp{} }
func (m *GetTargetsResp) String() string { return proto.CompactTextString(m) }
func (*GetTargetsResp) ProtoMessage()    {}
func (*GetTargetsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_310fea15e9cc3ce8, []int{5}
}

func (m *GetTargetsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetsResp.Unmarshal(m, b)
}
func (m *GetTargetsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetsResp.Marshal(b, m, deterministic)
}
func (m *GetTargetsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetsResp.Merge(m, src)
}
func (m *GetTargetsResp) XXX_Size() int {
	return xxx_messageInfo_GetTargetsResp.Size(m)
}
func (m *GetTargetsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetsResp proto.InternalMessageInfo

func (m *GetTargetsResp) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func init() {
	proto.RegisterType((*GetVPsReq)(nil), "GetVPsReq")
	proto.RegisterType((*GetVPsResp)(nil), "GetVPsResp")
	proto.RegisterType((*Source)(nil), "Source")
	proto.RegisterType((*GetTargetsReq)(nil), "GetTargetsReq")
	proto.RegisterType((*IPAddress)(nil), "IPAddress")
	proto.RegisterType((*GetTargetsResp)(nil), "GetTargetsResp")
}

func init() {
	proto.RegisterFile("rankingservice.proto", fileDescriptor_310fea15e9cc3ce8)
}

var fileDescriptor_310fea15e9cc3ce8 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0xed, 0x36, 0x89, 0x27, 0xbf, 0x5f, 0x0a, 0xab, 0x82, 0x4c, 0x24, 0x24, 0xcb, 0x1c,
	0xb0, 0x22, 0xe1, 0x43, 0xb8, 0x71, 0xe3, 0x42, 0xe9, 0x01, 0x11, 0x2d, 0x55, 0xaf, 0xd1, 0xe2,
	0x8c, 0xdc, 0x01, 0x67, 0xed, 0xee, 0xac, 0x2b, 0x72, 0xe1, 0x4b, 0xf0, 0x31, 0xf8, 0x92, 0xc8,
	0xeb, 0x3f, 0x4d, 0x05, 0x37, 0xbf, 0xe7, 0xd9, 0xa7, 0xf7, 0xde, 0x0c, 0x5c, 0x18, 0xa5, 0xbf,
	0x93, 0x2e, 0x18, 0xcd, 0x3d, 0xe5, 0x98, 0xd5, 0xa6, 0xb2, 0x55, 0xf2, 0xcb, 0x83, 0xf0, 0x12,
	0xed, 0xcd, 0x86, 0x25, 0xde, 0x89, 0x05, 0xf8, 0x54, 0x47, 0x5e, 0xec, 0xa5, 0xa1, 0xf4, 0xa9,
	0x16, 0xcf, 0x61, 0xa2, 0x9b, 0xfd, 0xcd, 0x86, 0x23, 0x3f, 0xf6, 0xd2, 0x33, 0xd9, 0x23, 0xb1,
	0x82, 0x27, 0xbd, 0xda, 0x35, 0xe6, 0xb7, 0x9a, 0xee, 0x1a, 0x8c, 0x02, 0xf7, 0xea, 0x2f, 0x5e,
	0xac, 0xe1, 0x02, 0x7f, 0x60, 0xde, 0x58, 0xdc, 0x7d, 0x42, 0xc5, 0x8d, 0xc1, 0x3d, 0x6a, 0xcb,
	0xd1, 0x69, 0x1c, 0xa4, 0xa1, 0xfc, 0xe7, 0xbf, 0xe4, 0x35, 0xc0, 0x60, 0x8a, 0x6b, 0xf1, 0x02,
	0x82, 0xfb, 0x9a, 0x23, 0x2f, 0x0e, 0xd2, 0xf9, 0x7a, 0x9a, 0x7d, 0xa9, 0x1a, 0x93, 0xa3, 0x6c,
	0xb9, 0xe4, 0x27, 0x4c, 0x3a, 0x28, 0x96, 0x30, 0xbb, 0xad, 0xd8, 0x6a, 0xb5, 0xc7, 0x3e, 0xc0,
	0x88, 0xfb, 0x58, 0xfe, 0x18, 0x4b, 0xc0, 0x29, 0x93, 0x1d, 0x2c, 0xbb, 0x6f, 0x11, 0xc1, 0x94,
	0x74, 0x61, 0x90, 0x5b, 0x67, 0x2d, 0x3d, 0xc0, 0x56, 0x79, 0x47, 0x6c, 0x95, 0xce, 0x31, 0x3a,
	0x8b, 0xbd, 0xd4, 0x97, 0x23, 0x4e, 0x7e, 0x7b, 0xf0, 0xff, 0x25, 0xda, 0x6b, 0x65, 0x0a, 0xb4,
	0xae, 0xc2, 0x97, 0x00, 0xc4, 0x5b, 0xd2, 0x64, 0x49, 0x95, 0xce, 0xc9, 0x4c, 0x86, 0xc4, 0x57,
	0x1d, 0x21, 0x56, 0xf0, 0x94, 0x78, 0x5b, 0xe9, 0xf2, 0xb0, 0x55, 0xbb, 0x5d, 0xab, 0x8f, 0x5d,
	0xb9, 0x33, 0x79, 0x4e, 0xfc, 0x59, 0x97, 0x87, 0xf7, 0x03, 0x2d, 0xde, 0xc0, 0x7f, 0x54, 0x1f,
	0x8d, 0x05, 0xae, 0x00, 0xc8, 0xae, 0x36, 0xfd, 0x8c, 0x9c, 0x53, 0xfd, 0x30, 0x1e, 0xc3, 0xbc,
	0x30, 0x4a, 0x37, 0xa5, 0x32, 0x64, 0x0f, 0x7d, 0x8a, 0x63, 0x2a, 0x59, 0x41, 0x38, 0xbe, 0x75,
	0x46, 0x47, 0xf5, 0xbe, 0xb2, 0x70, 0xd4, 0x4b, 0x56, 0xb0, 0x38, 0x0e, 0xc6, 0x75, 0xdb, 0x90,
	0xed, 0xa0, 0x5b, 0x45, 0x28, 0x07, 0xb8, 0xfe, 0x06, 0x53, 0xd9, 0xad, 0x5d, 0xbc, 0x82, 0x49,
	0xe1, 0x36, 0x27, 0x20, 0x1b, 0xef, 0x6a, 0x39, 0xcf, 0x1e, 0xd6, 0x99, 0x9c, 0x88, 0x77, 0xf0,
	0xac, 0x18, 0xb5, 0x3f, 0x98, 0x6a, 0xff, 0x91, 0x6c, 0x49, 0x6c, 0xc5, 0x22, 0x7b, 0x54, 0xe6,
	0xf2, 0x3c, 0x7b, 0xec, 0x21, 0x39, 0xf9, 0x3a, 0x71, 0x77, 0xfb, 0xf6, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0xd1, 0x45, 0xea, 0xcf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RankingClient is the client API for Ranking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankingClient interface {
	// Get VPs in a ranked way.
	//
	// The user provides the list of measurements executed so far,
	// so that the ranking service can always return the best option for the
	// provided situation.
	GetVPs(ctx context.Context, in *GetVPsReq, opts ...grpc.CallOption) (*GetVPsResp, error)
	// Get the target lists from a hitlist file
	GetTargetsFromHitlist(ctx context.Context, in *GetTargetsReq, opts ...grpc.CallOption) (*GetTargetsResp, error)
}

type rankingClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingClient(cc grpc.ClientConnInterface) RankingClient {
	return &rankingClient{cc}
}

func (c *rankingClient) GetVPs(ctx context.Context, in *GetVPsReq, opts ...grpc.CallOption) (*GetVPsResp, error) {
	out := new(GetVPsResp)
	err := c.cc.Invoke(ctx, "/Ranking/getVPs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) GetTargetsFromHitlist(ctx context.Context, in *GetTargetsReq, opts ...grpc.CallOption) (*GetTargetsResp, error) {
	out := new(GetTargetsResp)
	err := c.cc.Invoke(ctx, "/Ranking/getTargetsFromHitlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServer is the server API for Ranking service.
type RankingServer interface {
	// Get VPs in a ranked way.
	//
	// The user provides the list of measurements executed so far,
	// so that the ranking service can always return the best option for the
	// provided situation.
	GetVPs(context.Context, *GetVPsReq) (*GetVPsResp, error)
	// Get the target lists from a hitlist file
	GetTargetsFromHitlist(context.Context, *GetTargetsReq) (*GetTargetsResp, error)
}

// UnimplementedRankingServer can be embedded to have forward compatible implementations.
type UnimplementedRankingServer struct {
}

func (*UnimplementedRankingServer) GetVPs(ctx context.Context, req *GetVPsReq) (*GetVPsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVPs not implemented")
}
func (*UnimplementedRankingServer) GetTargetsFromHitlist(ctx context.Context, req *GetTargetsReq) (*GetTargetsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargetsFromHitlist not implemented")
}

func RegisterRankingServer(s *grpc.Server, srv RankingServer) {
	s.RegisterService(&_Ranking_serviceDesc, srv)
}

func _Ranking_GetVPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVPsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetVPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ranking/GetVPs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetVPs(ctx, req.(*GetVPsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_GetTargetsFromHitlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).GetTargetsFromHitlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ranking/GetTargetsFromHitlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).GetTargetsFromHitlist(ctx, req.(*GetTargetsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ranking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ranking",
	HandlerType: (*RankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getVPs",
			Handler:    _Ranking_GetVPs_Handler,
		},
		{
			MethodName: "getTargetsFromHitlist",
			Handler:    _Ranking_GetTargetsFromHitlist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rankingservice.proto",
}
